apiVersion: v2
type: application
name: dex
version: 0.8.0
appVersion: "2.31.1"
kubeVersion: ">=1.14.0-0"
description: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable connectors.
icon: https://dexidp.io/favicon.png
keywords:
  - oidc
  - oauth
  - identity-provider
  - saml
home: https://dexidp.io/
sources:
  - https://github.com/dexidp/dex
  - https://github.com/dexidp/helm-charts/tree/master/charts/dex
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Updated Dex version
  artifacthub.io/images: |
    - name: dex
      image: ghcr.io/dexidp/dex:v2.31.1
